# Generated by Django 2.0.4 on 2018-04-23 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playgroup', '0002_auto_20180423_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('playgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroup.PlayGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='event.Event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playgroup.Membership')),
            ],
        ),
    ]
