# Generated by Django 2.0.4 on 2018-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='response',
            field=models.CharField(choices=[('NR', 'Not responded'), ('YE', 'Yes'), ('NO', 'No')], default='NR', max_length=2),
        ),
    ]
