# Generated by Django 2.0.4 on 2018-04-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_invitation_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
